// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfcp0bLWUyoIiY89vlIt2ct4XdALq-tys',
    appId: '1:1039033999834:web:0c08d35d7622495661a0e3',
    messagingSenderId: '1039033999834',
    projectId: 'gbshoppinglist-def4a',
    authDomain: 'gbshoppinglist-def4a.firebaseapp.com',
    storageBucket: 'gbshoppinglist-def4a.appspot.com',
    measurementId: 'G-M2LTWG9NV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUVvRuUxpHEh_1pS_Wp2i9TlfH3j-wOfQ',
    appId: '1:1039033999834:android:ef24801bd4077a1e61a0e3',
    messagingSenderId: '1039033999834',
    projectId: 'gbshoppinglist-def4a',
    storageBucket: 'gbshoppinglist-def4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY817uPh_OsdTKYm5KQuZQEHHOCDAxgPA',
    appId: '1:1039033999834:ios:c7ba14c75a87575c61a0e3',
    messagingSenderId: '1039033999834',
    projectId: 'gbshoppinglist-def4a',
    storageBucket: 'gbshoppinglist-def4a.appspot.com',
    iosClientId: '1039033999834-4dptr09n0hsmqtnhr7bo3e175g50u5l7.apps.googleusercontent.com',
    iosBundleId: 'pl.skrzyp33k.gbShoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY817uPh_OsdTKYm5KQuZQEHHOCDAxgPA',
    appId: '1:1039033999834:ios:c7ba14c75a87575c61a0e3',
    messagingSenderId: '1039033999834',
    projectId: 'gbshoppinglist-def4a',
    storageBucket: 'gbshoppinglist-def4a.appspot.com',
    iosClientId: '1039033999834-4dptr09n0hsmqtnhr7bo3e175g50u5l7.apps.googleusercontent.com',
    iosBundleId: 'pl.skrzyp33k.gbShoppingList',
  );
}
